### ISSUE TITLE
Exposure level indicator

### ISSUE THREAD

**Issue by tho068** [mvmn/gp2srv#12]
Hello

Does this server support exposure level indicator?

**Comment by mvmn** [comment]
Hi

It depends on your camera. But what do you mean by "exposure level indicator" specifically? A reading from an in-camera light meter? Or just an exposure in seconds set on camera?

**Comment by tho068** [comment]
I was talking about an in camera light meter.

I am using a Canon 5d mark 3

I cannot see that it is outputted on the website, and I dont think it was listen under gphoto2 list all configs.

Do you know anything about this camera model? Or can you offer some advice as to which camera to choose?

**Comment by mvmn** [comment]
If gphoto2 list all configs doesn't show it - it won't be present in the web interface too. 

One workaround to get the light metering is to go to the scripts tab and create a script that would capture preview and then use __lightmeter.getForThumb(__capturedFile) for getting average lighting value of the captured preview image.
