### ISSUE TITLE
My goal for Gphoto2 server.

### ISSUE THREAD

**Issue by stargeezer55** [mvmn/gp2srv#14]
This is not an issue with Gphoto2Server. It works perfectly!
I am an amateur astro-photographer. Using Gphoto2, I am able to setup aperture, F stop, shutter speed etc. 
In addition, I can use it to capture multiple images using the same settings and download same for post processing. 
 I have only a rudimentary grasp of scripting and would like to use the web ui for it's ease of use.
My question is: How do I configure the web ui to capture a succession of images?
Does anyone know how I can set that up?
Thanks
Doug

**Comment by mvmn** [comment]
This can de done using "scripting" feature of GPhoto2Server. I'll make a video tutorial on it when I have time - it's rather complicated.

**Comment by stargeezer55** [comment]
Thank you. Eludes me for sure. 
I'm sure your busy so really no rush.
Doug
