### ISSUE TITLE
Download on script

### ISSUE THREAD

**Issue by edombek** [mvmn/gp2srv#15]
Is it possible to capture and download directly in the script?

**Comment by edombek** [comment]
I found a download method, but I do not understand how it is used
![изображение](https://user-images.githubusercontent.com/22872609/183872472-9fe1e1dd-130f-4576-9ab3-bfa02f72e940.png)

**Comment by mvmn** [comment]
Hello Evgeniy,

If you want support from Ukrainian developers you must first withdraw russian military from Ukraine, stop killing Ukrainian civillians en masse, and submit your criminal "leadership" for an international trial.
