### ISSUE TITLE
Live View isn't working in MS Edge

### ISSUE THREAD

**Issue by tarnis** [mvmn/gp2srv#4]
Installed 2.6, live view no longer seems to stream like it did in 1.4.  If I turn it off and on again it will update so I'm guessing the video is just not streaming from my Canon 5D mkIII.  

And not really a bug, but would be nice if the capture target defaulted to the memory card rather than internal ram.  Not sure why anyone would choose internal ram, or if there is a way for myself to make it the default.

**Comment by mvmn** [comment]
> live view no longer seems to stream 

Can you try opening http://<your_gp2server_host:port>/stream.mjpeg directly?
Can you also check if there are any errors in console when you open live view?

> would be nice if the capture target defaulted to the memory card rather than internal ram.

I get this setting from GPhoto2 library, so it should reflect what's set in the camera currently (like all other settings - ISO, shutter speed, aperture etc).

**Comment by tarnis** [comment]
OK, it seems to be an issue with MS Edge, it does work in Chrome.

The save location is not something I can set in the camera though.  Are you
saying you do not need to do this?  I've seen other tutorials on gphoto2
and sending commands from the Raspberry Pi via command line and this is one
of the first commands that needs to be done, so I figured it was just
something that needed to be set earlier in the script.

In other news, I'd love to help you maybe with the UI.  I downloaded the
code and couldn't find any html files.  Never really delt with a Java app
before so I'm not sure I'm going to find what I'm looking for,  I am not
much of a programmer, but do design websites.  If you could tell me where I
could find the .CSS file I can maybe see what I can do?

Regards,
Matt

**Comment by mvmn** [comment]
> OK, it seems to be an issue with MS Edge, it does work in Chrome.

MS browsers are always... special :D 

> I've seen other tutorials on gphoto2
and sending commands from the Raspberry Pi via command line and this is one
of the first commands that needs to be done

Actually in GP2Server I don't set any configs unless user tells me to do it via UI. The configs are read and current values are presented, but nothing is set (changed) unless user explicitly chooses to. It's actually weird you have internal RAM there by default. If you set that to SD card via GP2Server, does it reset back to internal RAM on restart? Well, I could set it automatically, but thing is every camera may have different configs, for some cameras capture target config might not exist, or have different name/key, or have differently named and/or differently ordered options.

> In other news, I'd love to help you maybe with the UI.

That'd be nice. Take a look into src/main/resources/x/mvmn/gp2srv/web folder, there are two subfolders there - static and templates. The "static" contains css and images (and JS files), and templates contains serverside templates in [Apache Velocity](http://velocity.apache.org/engine/1.7/user-guide.html) format (very few of it is used in v. 2+, so hopefully you won't actually have to deal with it much), and clientside templates for JS library [Ractive](http://www.ractivejs.org) (mostly UI is rendered with those now). As well as some relatively ugly JavaScript for handing UI (in index.vm).

If you can make sense of it and make stuff better - pull requests are more than welcome!

**Comment by tarnis** [comment]
It used to work, I didn't think to check before I asked :)  But yes, they
are.

Neither version for me has saved any settings from one time to the next, do
I maybe have the permissions set wrong on a directory?

Will download the code and have a look maybe over the weekend.

**Comment by mvmn** [comment]
> Neither version for me has saved any settings from one time to the next, do
I maybe have the permissions set wrong on a directory?

Nope, the idea was that camera will keep it's own settings. I'm not saving any of those into filesystem, I'm just setting those in camera.

Think of it this way - you have a camera with specific values for aperture, ISO, shutter speed etc. You connect it to GPhoto2Server and what you'll get in settings are those values - since that's what they are in camera, and if you do capture the capture will be done with those values.

If you change any of those in GPhoto2Server the changes are applied in camera, so that when you capture again the shot will be done with new values.

Then even if you disconnect camera from PC those values should remain set in camera.

At no point there is a reason to save anything to filesystem.

**Comment by mvmn** [comment]
Hm, I've found out that gphoto2 may actually save some settings in [user home]/.gphoto/settings file. Can you check whether this file exists, and if it does - what's the content of it?

**Comment by mvmn** [comment]
P.S. Actually it seems you might need permissions to that folder to save capture target. For some reason this is the only setting gphoto2 seems to actually store in local FS.

**Comment by tarnis** [comment]
My Linux is OK, but mildly lost...

.gphoto directory I think I have read, write, execute - drwx------

settings has -rw-r--r-- so I think I should be able to read and write that
one as well?

OR does Other need read/write permission since it's running in the
background? chmod 766?

Thanks,
Matt

**Comment by mvmn** [comment]
I think you should just delete .gphoto directory and see if and settings file inside it will be re-created when you start GPhoto2Server. If yes, try changing capture target to SD card and checking whether it remains that after GPhoto2Server restarts.

**Comment by tarnis** [comment]
Same problem still.  It's not as bad once I realized what the favorites and
checkboxes were, more mildly annoying now.

FYI the settings file in the .gphoto directory I deleted said Memory Card,
and the directory was not recreated.  Not sure where or if it's saving
settings now.


[image: Inline image 1]

**Comment by mvmn** [comment]
> the directory was not recreated

This probably means there are insufficient rights to create/update .gphoto directory in user home. Hence settings file not being saved/updated, hence capture target not being stored.

**Comment by tarnis** [comment]
This is fresh out of the box raspian lite.

What should I set the home directory to be?  It is:
drwxr-xr-x

**Comment by tarnis** [comment]
After changing the home directory to 777 read/write/execute for all it
still didn't create the directory.

I'm launching the server on startup rom /etc/init.d/mystartup.sh ...Perhaps
the directory is being created elsewhere?

**Comment by tarnis** [comment]
hmmm...so all those directories are being created in /root.  Do I need to
change the user type I'm logging in as...or since it's running as root
shouldn't it already know?

**Comment by mvmn** [comment]
> Perhaps the directory is being created elsewhere?

Might be. Init.d does not necessarily use your user to create the process.
I know there is some way to tell it which user to run process as, but I'm not so proficient with init.d.

**Comment by mvmn** [comment]
> all those directories are being created in /root

Aha, that means init.d runs it as root by default.
Still, since directories are being created, I'm not sure why saving of capture target doesn't happen.

Can you post contents of /root/.gphoto/settings file?

**Comment by tarnis** [comment]
If you were running this headless, where would you have it startup?

There is just a .gphoto directory, no settings file.  I guess I can change
the permissions to that directory to 751 and maybe I'll be able to write to
it.

**Comment by mvmn** [comment]
> If you were running this headless, where would you have it startup?

Doesn't matter much I guess, but it's safer to not run as root I suppose. Any user that isn't root, you can even create dedicated user - that'd be most secure I think.

**Comment by mvmn** [comment]
> no settings file

This probably is the root cause.

**Comment by tarnis** [comment]
Have you tried running this headless?

**Comment by mvmn** [comment]
No, not yet.

**Comment by tarnis** [comment]
I kinda had a question or two about gp2srv, but not really related to this issue...or entirely what you've been doing :).  Wasn't sure how I might otherwise contact you?
