### ISSUE TITLE
Capture and Download Images to the raspberry pi

### ISSUE THREAD

**Issue by Traumwelttv** [mvmn/gp2srv#5]
Hey there...
is it possible to capture a photo and download it automatically to a specefic folder on the raspberry pi? Like the cli command "--capture-image-and-download".

**Comment by mvmn** [comment]
Not yet. I'll add this feature in future.

**Comment by mvmn** [comment]
Added the feature in v2.7
https://github.com/mvmn/gp2srv/releases/tag/2.7

**Comment by Traumwelttv** [comment]
Nice...thanks man! Great Job at all👍

**Comment by mvmn** [comment]
Welcome
P.S. Quick demo of the feature - shooting without SD card into internal RAM, with download to PC (Raspberry Pi in this case) and deletion from internal RAM
https://www.youtube.com/watch?v=K-yDAjcCxnM
